packages:
  - 'packages/*'
  - 'docs'

catalog:
  # React (stable version 18)
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  
  # Build tools
  typescript: ^5.7.3
  vite: ^6.1.0
  tsup: ^8.3.5
  '@vitejs/plugin-react': ^4.3.4
  
  # Testing
  vitest: ^2.1.8
  '@vitest/ui': ^2.1.8
  
  # Code quality
  eslint: ^9.20.1
  prettier: ^3.5.0
  
  # Utils
  classnames: ^2.5.1
  
  # Docusaurus
  '@docusaurus/core': ^3.7.0
  '@docusaurus/preset-classic': ^3.7.0
