packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  # React 19 (latest)
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3

  # Build tools
  typescript: ^5.7.3
  vite: ^6.1.0
  tsup: ^8.3.5
  '@vitejs/plugin-react': ^4.3.4
  vite-plugin-dts: ^4.4.0

  # Testing
  vitest: ^2.1.8
  '@vitest/ui': ^2.1.8
  '@testing-library/react': ^16.2.0
  '@testing-library/jest-dom': ^6.6.3

  # Code quality
  eslint: ^9.20.1
  prettier: ^3.5.0

  # CSS
  tailwindcss: ^3.4.17
  postcss: ^8.5.0
  autoprefixer: ^10.4.20
  less: ^4.2.0

  # Utils
  classnames: ^2.5.1

  # Docusaurus
  '@docusaurus/core': ^3.7.0
  '@docusaurus/preset-classic': ^3.7.0
